### ISSUE TITLE
Ethiohri technical roadmap

### ISSUE THREAD

**Issue by aman-icap** [CDC-HIS/openmrs-esm-ethiohri#60]
**Feature Work**
- [ ] Registration page
  - [x] Support editing/removing built in fields ( remove "Patient name is known" )
  - [x] Support adding obs fields of all types (numeric, date, coded)
  - [x] Support displaying identifier fields even when not required
  - [x] Implement Ethiopian calendar date picker
  - [ ] Insert "Megabit 1st" as opposed to "January 1st" for patients with unkonwn birth dates
 
- [ ] UI 
  - [x] Fix local server instance to load Ethiohri with the proper overrides
  - [x] Moving from edit to view mode on forms fails with error
  - [x] Cancel button not working properly, Confirm button in cancel do nothing
  - [x] Hiding/unhiding dashboard menus using custom expressions written in Ethiohri is not possible, can only use expressions written on the form engine. 
 
- [ ] Forms
  - [x] Limiting forms like Intake A to be filled only once
  - [x] Support restricting  forms from being filled if patient has incomplete registration information
  - [x] Forms don't have delete option
  - [ ] Form's don't have print option
  - [ ] Make "required" property conditional in reference to questions and answers.
  - [x] Implement hideExpression on answers
  
**Bugs**
- [ ] Forms
   - [x] Display forms in full screen window instead of minized version
   - [x] Previewing values of repeating fields in encounter list is not possible
   - [x] Hide logic not working on pages and sections in edit mode
   - [x] Random previous values show when a new form is added, new forms should not show any values
   - [x] Add button on forms can't be hidden if there isnt atleast one encounter for that specific encounter type.
   - [x] Datepicker does not open when form is expanded
   - [ ] Forms should open up expanded by default
   - [x] Custom date validations using js_expressions don’t work when using async custom expressions 

**Support**
   - [x] New forms or edited forms do not display the ‘Add’ button without clear errors. Need support on best practices of managing forms on the backend.  
   - [x] Usage of role-based authorization for different modules such as ART and PMTCT.

**Comment by gracepotma** [comment]
It would be really really helpful to see here precisely:
* which ones are critical - sounds like Registration Page and Ethiopian Calendar?
* the source of each problem (e.g. is it specifically related to the React Form Engine, or is it related to the foundational O3 RefApp, or is it a feature that can be built using the shared O3 engineering approach?)
